### ISSUE TITLE
Use eslint cli api instead of standard

### ISSUE THREAD

**Issue by sheerun** [KidkArolis/healthier#10]
Most software is better ingregrated with eslint output rather than standard's

**Comment by KidkArolis** [comment]
I would then have to deviate from standard-engine? Which is ok, I guess.

Do you mean the textual linting output in the console? Do you have a use case in mind? Which software?

Btw, thanks for all these suggestions!

**Comment by sheerun** [comment]
Yes because standard-engine is far less popular than eslint itself.

The integration isn't very complicated, you can copy my commented code from prettier-standard which is work in progress, but mostly works: https://github.com/sheerun/prettier-standard/blob/master/src/cli.js#L78
