### ISSUE TITLE
Consider auto detecting react and adding standard-react rules

### ISSUE THREAD

**Issue by KidkArolis** [KidkArolis/healthier#20]
The main reason I haven't done this yet is because it would make healthier incompatible with standard. Up until now, anything that conforms to standard was also conforming to healthier.

But maybe that's not a big deal. It's all about good defaults, good user experience, etc.

The other reason is that prop-types validation is a bit invasive, I usually don't use it in my apps. So again, I don't want to be caught in the position of making decisions on rules without sort of leaning on standard, where people spend more effort arguing for each rule, etc.

**Comment by KidkArolis** [comment]
Also, see #16 for more background discussion.

**Comment by sheerun** [comment]
Why it would not confirm to standard? All standard rules would be preserver, you'd be adding something on top of standard rules only

**Comment by KidkArolis** [comment]
standard test.js -> 0 errors
healthier test.js -> 3 errors

^ that's what I mean by not compatible

**Comment by sheerun** [comment]
Well, my vote is to provide good linting defaults, not 100% match with standard.js

**Comment by sheerun** [comment]
lynt seems like solid alternative for react stack. maybe you could join efforts, or take lynt config and sprinkle extra stuff on top of it, or just expand on it. I really like that lynt agreed to introduce and auto detection of jest / flow / react / typescript / vue https://github.com/saadq/lynt/issues/41

**Comment by sheerun** [comment]
btw. I like healthier approach of merging different plugins better - lynt needs to maintain these configs while you can focus on creating nice umbrella package

As for prop-types rule I agree it is too strict, you could extend https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app instead or make this rule a warning and introduce another `--warnings` flag that shows them. I think you can decide to include / exclude some rules if there's good reason, after all it's opinionated package.

IMO it would be great if healthier adapted "zero config approach" for developers that use popular libraries and tools like react / vue / jest etc.

**Comment by KidkArolis** [comment]
Added this feature to healthier@3.2.0. If React is detected, healthier will turn on extra rules (`standard-react`, `react-hooks` and some from `react-app`). Auto detection is not done in `eslint-config-healthier` but there you can turn same rules by extending `healthier/react` in addition to `healthier`.
