### ISSUE TITLE
Lots of warnings for eslint-config-healthier when using yarn

### ISSUE THREAD

**Issue by sheerun** [KidkArolis/healthier#22]
I was wrong that there wouldn't be any warnings when packages are flattened. It seems that npm doesn't product any warnings, but yarn does:

```
yarn add eslint eslint-config-healthier
yarn add v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "eslint-config-healthier > eslint-config-standard-jsx@6.0.2" has unmet peer dependency "eslint-plugin-react@>=7.11.1".
warning "eslint-config-healthier > eslint-config-standard-react@7.0.2" has unmet peer dependency "eslint-plugin-react@>=7.6.1".
warning "eslint-config-healthier > eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-import@>=2.13.0".
warning "eslint-config-healthier > eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-node@>=7.0.0".
warning "eslint-config-healthier > eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-promise@>=4.0.0".
warning "eslint-config-healthier > eslint-config-standard@12.0.0" has unmet peer dependency "eslint-plugin-standard@>=4.0.0".
```

Maybe reconsider vendoring these packages

**Comment by KidkArolis** [comment]
Yeah, should be easy enough, thanks for flagging.

**Comment by KidkArolis** [comment]
Just a stream of thoughts..

Had another look into this. Still a pain to create rich shareable configs and plugins in eslint. Still a bunch of peer dependency warnings. I could try vendoring (I don't want to copy entire node_modules, I'd need to pull in the source and dependencies via some script, but if dependencies clash, not gonna be easy) or I could just continue waiting until eslint supports this out of the box.

In the meantime, this still works, despite the warnings.

Also, if you use the `healthier` binary, things work well. You only get warnings if you try and pull in extra rules, e.g. installing `eslint-config-healthier` to use `healthier/react` or installing `eslint-config-standard-react` triggers peer dependency warnings about unmet eslint, eslint-plugin-react, and others.

I like how standard makes life easier by just saying "no configuration" to avoid these pains (at the cost of not being able to use more rules such as `css-modules`, `jsx-a11y`, `react` or `react-hooks`.. and probably many more.

I guess this remains an open question for now.

**Comment by sheerun** [comment]
Recent version of prettier-standard supports `--lint` flag and uses most dependencies you're using without warnings because it bundles all eslint dependencies within published package. Basically I use following .npmignore and publish with recent npm:

```
!src/vendor/node_modules
!src/vendor/node_modules/
!src/vendor/node_modules/**
```
