### ISSUE TITLE
Can we add a babel-eslint dependency?

### ISSUE THREAD

**Issue by NathanielHill** [KidkArolis/healthier#25]
What's the reasoning behind including `eslint-config-standard-jsx` but not `babel-eslint` to be able to parse JSX?

**Comment by KidkArolis** [comment]
Thats a good question. Maybe theres a penalty for including it for non jsx projects, eg node. Basically, this is what standard does, and I haven’t deviated from their behaviour. I’ll check their issues for any past discussion on this.

**Comment by KidkArolis** [comment]
Actually, just checked, and jsx parsing works in vanilla healthier/standard, e.g.:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/324440/53491149-8e143700-3a8d-11e9-8258-2ce22272f901.png">

So using `babel-eslint` is only needed when using non standard JavaScript features.

**Comment by KidkArolis** [comment]
Is this still an issue for you or can I close?

**Comment by NathanielHill** [comment]
Yeah, good point. Looks like it's because I'm using class properties :man_facepalming:

**Comment by NathanielHill** [comment]
I think that's the only thing. Making me reconsider class fields :thinking:
