### ISSUE TITLE
Add unused imports linting

### ISSUE THREAD

**Issue by NathanielHill** [KidkArolis/healthier#26]
Only difference I've noticed from `standard` in terms of linting, is I am not getting unused import warnings with healthier. Is this intentional?

**Comment by KidkArolis** [comment]
You should be getting those. Could you provide a small snippet of code where you're experiencing that issue so that I could try and reproduce locally?

**Comment by NathanielHill** [comment]
@KidkArolis I'm not getting them anywhere in my project. I suspect it's my setup not the code.

**Comment by KidkArolis** [comment]
Do you get other lint errors?

Also, there is no no-unused-imports rule afaik? (https://eslint.org/docs/rules/)

And this does work:

```
$ echo 'import a from "b"; console.log()' | healthier --stdin

<text>
  1:8  error  'a' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

Anyway, let me know if I can help.

**Comment by NathanielHill** [comment]
Yeah, I guess they we're being caught with the `no-unused-vars` and `no-undef` rules.

I am getting all other linting, but interestingly if I run `echo 'import a from "b"; console.log()' | healthier --stdin` in the project root, I don't get any errors!

**Comment by KidkArolis** [comment]
Do you have an .eslintrc in your project (or perhaps some parent dir)?

**Comment by NathanielHill** [comment]
No `.eslintrc` or config anywhere.

I have the following in my root `package.json`:

```
"prettier": {
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "jsxSingleQuote": true
}
```

**Comment by NathanielHill** [comment]
I believe this was related to needing `babel-eslint` but not having it installed. Closing

**Comment by KidkArolis** [comment]
Ah, phew 😅

**Comment by NathanielHill** [comment]
Haha, of course now the vscode extension is troubling me :man_facepalming:
