### ISSUE TITLE
Semistandard documentation

### ISSUE THREAD

**Issue by bnjmnrsh** [KidkArolis/healthier#35]
Hi @KidkArolis 👋🏼
I was really happy to see your encouraging comment on the standard repo [feat: add prettier support #231](https://github.com/standard/standard-engine/pull/231#issuecomment-825945342)! 

My comments in that thread came out of the bewilderment of realizing that while the standard and prettier projects are so closely aligned philosophically, somehow they just haven't decided to play well together all these years! 

In regards to your project Healthier, my interest has been in using [semistandard](https://github.com/standard/semistandard), because frankly, the semicolons argument at work is proving too divisive! 😂

I've only just now read the Healthier docs but as understand it, achieving the same results as `semistandard`, would mean simply setting the `.prettierrc` to `{"semi": true,}`?

Is that an oversimplification of the `semistandard` rule set?

**Comment by KidkArolis** [comment]
I think that's it! Healthier will not warn about semis or lack of. So it's up to prettier to format one way or the other. In fact, you don't even need .prettierrc in your case, prettier formats with semi columns by default, I only shared the example .prettierrc in the README to show what kind of prettier config brings you closer to standard formatting, but it's up to you. I hope that makes sense.

And to check that files correctly lint _and_ are formatted, I use this lint script in my package.json:

```json
{
  "scripts": {
    "lint": "healthier && prettier --check '**/*.{js,json,css,yml}'",
    "format": "prettier --write '**/*.{js,json,css,yml}'",
  }
}
```

Healthier lints using all non code style standard rules (which are the same in semistandard). And `prettier --check` checks that files have in fact been formatted with prettier.
