### ISSUE TITLE
Add all framerwork-specific prettier configs

### ISSUE THREAD

**Issue by sheerun** [KidkArolis/healthier#9]
Not all possible whitespace rules are excluded, you need to iclude all prettier configs like described in their readme: https://www.npmjs.com/package/eslint-config-prettier

```
{
  "extends": [
    "some-other-config-you-use",
    "prettier",
    "prettier/babel",
    "prettier/flowtype",
    "prettier/react",
    "prettier/standard",
    "prettier/typescript",
    "prettier/unicorn",
    "prettier/vue"
  ]
}
```

**Comment by KidkArolis** [comment]
Interesting. Do I really need unicorn, since this is not using any of the unicorn rules? In fact I don't use any of the other ones either? Do you have a code snippet that you think would not work? I mean it would format by prettier but linter would fail.

**Comment by sheerun** [comment]
It won't matter until someone uses custom .eslintrc with vue/unicorn etc. config rules (the feature I think healthier should support).

Besides I think it would be in prettier's spirit to support all these additional configs by default (the same way prettier supports css/json/sass/typescript/vue etc. formatting by default)

**Comment by KidkArolis** [comment]
Ok, so we also need to decide if custom eslint rules should be allowed, and then yes, it starts mattering.

In standard's spirit, it shouldn't be supported ;) But yeah, I've been thinking about this and am very open. Basically Healthier would be .. a good foundation and defaults, but possible to tweak, e.g. react-a11y is very cool. Matches philosophy of https://github.com/KidkArolis/jetpack/ too..

**Comment by KidkArolis** [comment]
Will add the extra prettier configs as suggested. They are useful if using certain plugins.

But need to double check if say adding prettier/typescript would error with "missing eslint-plugin-typescript" or smth like that. In that case, it's a no go..
